<fmmarques> Hi all. I really need to install the Ubuntu fglrx .deb in Jessie. How can i accomplish this?
<fmmarques> Ouroboros: it tells me the file is not a debian format...
<fmmarques> It is the closest format to debian that AMD gives out. The source package, which I tried to download to build and install the module, fails download.
